name: "Deploy"
on:
  push:
    branches: ["feature/first-cicd"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build page
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here, e.g., scp, rsync, etc.
          # Example:
          # scp -r ./dist
