name: "Hola Mundo Deploy"
on:
  push:
    branches: ["main"]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      - name: Obtener variable
        id: get_variable
        run: echo "The variable is ${{ steps.step_1.outputs.my_variable }}"
    outputs:
      my_variable: ${{ steps.step_1.outputs.my_variable }}
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    env:
      my_variable: ${{ needs.first-job.outputs.my_variable }}
    steps:
      - name: Step 2
        run: echo "The variable from the first job is ${{ env.my_variable }}"
