name: "Deploy"
on:
  push:
    branches: ["feature/first-cicd"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build page
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: public/
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4
