name: "Deploy"
on:
  push:
    branches: ["feature/first-cicd"]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo "${{ secrets.MY_SECRET }}"
      - name: Print variable
        run: echo "${{ env.MY_VARIABLE }}"
