name: "Deploy"
on:
  push:
    branches: ["feature/first-cicd"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build page
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: public/
  deploy:
    needs: build

    permissions:
      contents: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
